name: Test smrmgr.sh on Linux distros

on:
  push:
    branches:
      - pr/harden-install-script
    paths:
      - 'scripts/production/smrmgr.sh'
      - '.github/workflows/smrmgr.yaml'

jobs:
  test-on-distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu:latest
          - debian:latest
          - archlinux:latest
          - almalinux:9
          - redhat/ubi8:latest
    container:
      image: ${{ matrix.os }}

    steps:
      - name: Install common dependencies for specific OS
        run: |
          if command -v apt-get &>/dev/null; then
            apt-get update && apt-get install -y bash curl git
          elif command -v yum &>/dev/null; then
            yum install -y bash curl git
          elif command -v dnf &>/dev/null; then
            dnf install -y bash curl git
          elif command -v pacman &>/dev/null; then
            pacman -Sy --noconfirm bash curl git
          elif command -v emerge &>/dev/null; then
            echo 'Installing git and bash on Gentoo...'
            emerge dev-vcs/git app-shells/bash
          else
            echo "Unsupported package manager"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x scripts/production/smrmgr.sh

      - name: Test smrmgr.sh
        run: |
          curl -sL https://raw.githubusercontent.com/simplecontainer/smr/refs/heads/main/scripts/production/smrmgr.sh -o smrmgr
          chmod +x smrmgr
          sudo mv smrmgr /usr/local/bin 
          sudo smrmgr install
          smr version
          smrctl version

